const dummy_data = [
  {
    meals: [
      {
        idMeal: '53053',
        strMeal: 'Beef Rendang',
        Poster: '../../assets/images/food_1.png',
        strDrinkAlternate: null,
        strCategory: 'Beef',
        strArea: 'Malaysian',
        strInstructions:
          'Chop the spice paste ingredients and then blend it in a food processor until fine.\r\nHeat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat.\r\nLower the heat to low, cover the lid, and simmer for 1 to 1 1/2 hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg',
        strTags: null,
        strYoutube: 'https://www.youtube.com/watch?v=Ot-dmfBaZrA',
        strIngredient1: 'Beef',
        strIngredient2: 'Vegetable Oil',
        strIngredient3: 'Cinnamon Stick',
        strIngredient4: 'Cloves',
        strIngredient5: 'Star Anise',
        strIngredient6: 'Cardamom',
        strIngredient7: 'Coconut Cream',
        strIngredient8: 'Water',
        strIngredient9: 'Tamarind Paste',
        strIngredient10: 'Lime',
        strIngredient11: 'Sugar',
        strIngredient12: 'Challots',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '1lb',
        strMeasure2: '5 tbs',
        strMeasure3: '1',
        strMeasure4: '3',
        strMeasure5: '3',
        strMeasure6: '3',
        strMeasure7: '1 cup ',
        strMeasure8: '1 cup ',
        strMeasure9: '2 tbs',
        strMeasure10: '6',
        strMeasure11: '1 tbs',
        strMeasure12: '5',
        strMeasure13: ' ',
        strMeasure14: ' ',
        strMeasure15: ' ',
        strMeasure16: ' ',
        strMeasure17: ' ',
        strMeasure18: ' ',
        strMeasure19: ' ',
        strMeasure20: ' ',
        strSource:
          'https://rasamalaysia.com/beef-rendang-recipe-rendang-daging/',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52896',
        strMeal: 'Full English Breakfast',
        Poster: '../../assets/images/food_2.png',
        strDrinkAlternate: null,
        strCategory: 'Breakfast',
        strArea: 'British',
        strInstructions:
          "Heat the flat grill plate over a low heat, on top of 2 rings/flames if it fits, and brush sparingly with light olive oil.\r\nCook the sausages first. Add the sausages to the hot grill plate/the coolest part if there is one and allow to cook slowly for about 15-20 minutes, turning occasionally, until golden. After the first 10 minutes, increase the heat to medium before beginning to cook the other ingredients. If you are struggling for space, completely cook the sausages and keep hot on a plate in the oven.\r\nSnip a few small cuts into the fatty edge of the bacon. Place the bacon straight on to the grill plate and fry for 2-4 minutes each side or until your preferred crispiness is reached. Like the sausages, the cooked bacon can be kept hot on a plate in the oven.\r\nFor the mushrooms, brush away any dirt using a pastry brush and trim the stalk level with the mushroom top. Season with salt and pepper and drizzle over a little olive oil. Place stalk-side up on the grill plate and cook for 1-2 minutes before turning and cooking for a further 3-4 minutes. Avoid moving the mushrooms too much while cooking, as this releases the natural juices, making them soggy.\r\nFor the tomatoes, cut the tomatoes across the centre/or in half lengthways if using plum tomatoes , and with a small, sharp knife remove the green 'eye'. Season with salt and pepper and drizzle with a little olive oil. Place cut-side down on the grill plate and cook without moving for 2 minutes. Gently turn over and season again. Cook for a further 2-3 minutes until tender but still holding their shape.\r\nFor the black pudding, cut the black pudding into 3-4 slices and remove the skin. Place on the grill plate and cook for 1½-2 minutes each side until slightly crispy.\r\nFor 'proper' fried bread it's best to cook it in a separate pan. Ideally, use bread that is a couple of days old. Heat a frying pan to a medium heat and cover the base with oil. Add the bread and cook for 2-3 minutes each side until crispy and golden. If the pan becomes too dry, add a little more oil. For a richer flavour, add a knob of butter after you turn the slice.\r\nFor the fried eggs, break the egg straight into the pan with the fried bread and leave for 30 seconds. Add a good knob of butter and lightly splash/baste the egg with the butter when melted. Cook to your preferred stage, season and gently remove with a fish slice.\r\nOnce all the ingredients are cooked, serve on warm plates and enjoy straight away with a good squeeze of tomato ketchup or brown sauce.",
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/sqrtwu1511721265.jpg',
        strTags: 'Greasy,UnHealthy,HangoverFood,Calorific,Breakfast,BBQ',
        strYoutube: 'https://www.youtube.com/watch?v=FXjYU2Ensck',
        strIngredient1: 'Sausages',
        strIngredient2: 'Bacon',
        strIngredient3: 'Mushrooms',
        strIngredient4: 'Tomatoes',
        strIngredient5: 'Black Pudding',
        strIngredient6: 'Eggs',
        strIngredient7: 'Bread',
        strIngredient8: 'Baked Beans',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '4',
        strMeasure2: '4',
        strMeasure3: '4',
        strMeasure4: '3',
        strMeasure5: '2 sliced',
        strMeasure6: '2',
        strMeasure7: '1 Slice',
        strMeasure8: '100g ',
        strMeasure9: '',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: '',
        strMeasure17: '',
        strMeasure18: '',
        strMeasure19: '',
        strMeasure20: '',
        strSource:
          'https://www.bbc.co.uk/food/recipes/stressfreefullenglis_67721',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52877',
        strMeal: 'Lamb and Potato pie',
        Poster: '../../assets/images/food_3.png',
        strDrinkAlternate: null,
        strCategory: 'Lamb',
        strArea: 'British',
        strInstructions:
          'Dust the meat with flour to lightly coat.\r\nHeat enough vegetable oil in a large saucepan to fill the base, and fry the onion and meat until lightly browned. Season with salt and pepper.\r\nAdd the carrots, stock and more seasoning to taste.\r\nBring to the boil, cover and reduce the heat to a simmer. Simmer for at least an hour or until the meat is tender. Take your time cooking the meat, the longer you leave it to cook, the better the flavour will be.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nAdd the drained potato cubes to the lamb.\r\nTurn the mixture into a pie dish or casserole and cover with the shortcrust pastry. Make three slits in the top of the pastry to release any steam while cooking.\r\nBrush with beaten egg and bake for about 40 minutes, until the pastry is golden brown.\r\nServe.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/sxrpws1511555907.jpg',
        strTags: 'Pie',
        strYoutube: 'https://www.youtube.com/watch?v=NCyPaaUNYUk',
        strIngredient1: 'Lamb Shoulder',
        strIngredient2: 'Flour',
        strIngredient3: 'Vegetable Oil',
        strIngredient4: 'Onion',
        strIngredient5: 'Carrots',
        strIngredient6: 'Vegetable Stock',
        strIngredient7: 'Potatoes',
        strIngredient8: 'Shortcrust Pastry',
        strIngredient9: 'Eggs',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '500g',
        strMeasure2: '1 tbls',
        strMeasure3: 'Dash',
        strMeasure4: '1 sliced',
        strMeasure5: '2 sliced',
        strMeasure6: '350ml/12fl',
        strMeasure7: '500g',
        strMeasure8: '450g',
        strMeasure9: 'To Glaze',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: '',
        strMeasure17: '',
        strMeasure18: '',
        strMeasure19: '',
        strMeasure20: '',
        strSource: 'https://www.bbc.co.uk/food/recipes/lambandpotatopie_83913',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '53062',
        strMeal: 'Walnut Roll Gužvara',
        Poster: '../../assets/images/food_4.png',
        strDrinkAlternate: null,
        strCategory: 'Dessert',
        strArea: 'Croatian',
        strInstructions:
          'Mix all the ingredients for the dough together and knead well. Cover the dough and put to rise until doubled in size which should take about 2 hours. Knock back the dough and knead lightly.\r\n\r\nDivide the dough into two equal pieces; roll each piece into an oblong about 12 inches by 8 inches. Mix the filling ingredients together and divide between the dough, spreading over each piece. Roll up the oblongs as tightly as possible to give two 12 inch sausages. Place these side by side, touching each other, on a greased baking sheet. Cover and leave to rise for about 40 minutes. Heat oven to 200ºC (425ºF). Bake for 30-35 minutes until well risen and golden brown. Bread should sound hollow when the base is tapped.\r\n\r\nRemove from oven and brush the hot bread top with milk. Sift with a generous covering of icing sugar.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg',
        strTags: 'Nutty',
        strYoutube: 'https://www.youtube.com/watch?v=Q_akngSJVrQ',
        strIngredient1: 'Flour',
        strIngredient2: 'Caster Sugar',
        strIngredient3: 'Yeast',
        strIngredient4: 'Salt',
        strIngredient5: 'Milk',
        strIngredient6: 'Eggs',
        strIngredient7: 'Butter',
        strIngredient8: 'Walnuts',
        strIngredient9: 'Butter',
        strIngredient10: 'Brown Sugar',
        strIngredient11: 'Cinnamon',
        strIngredient12: 'Milk',
        strIngredient13: 'Icing Sugar',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '450g',
        strMeasure2: '55g',
        strMeasure3: '2 parts ',
        strMeasure4: '1/2 tsp',
        strMeasure5: '6 oz ',
        strMeasure6: '2 Beaten ',
        strMeasure7: '30g',
        strMeasure8: '140g',
        strMeasure9: '85g',
        strMeasure10: '85g',
        strMeasure11: '1 tsp ',
        strMeasure12: 'To Glaze',
        strMeasure13: 'To Glaze',
        strMeasure14: ' ',
        strMeasure15: ' ',
        strMeasure16: ' ',
        strMeasure17: ' ',
        strMeasure18: ' ',
        strMeasure19: ' ',
        strMeasure20: ' ',
        strSource:
          'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52981',
        strMeal: 'Snert (Dutch Split Pea Soup)',
        Poster: '../../assets/images/food_5.png',
        strDrinkAlternate: null,
        strCategory: 'Side',
        strArea: 'Dutch',
        strInstructions:
          'Gather the ingredients.\r\n\r\nIn a large soup pot, bring water, split peas, pork belly or bacon, pork chop, and bouillon cube to a boil. Reduce the heat to a simmer, cover and let cook for 45 minutes, stirring occasionally and skimming off any foam that rises to the top. \r\n\r\nRemove the pork chop, debone, and thinly slice the meat. Set aside.\r\n\r\nAdd the celery, carrots, potato, onion, leek, and celeriac to the soup. Return to the boil, reduce the heat to a simmer and let cook, uncovered, for another 30 minutes, adding a little extra water if the ingredients start to stick to the bottom of the pot.\r\n\r\nAdd the smoked sausage for the last 15 minutes of cooking time. When the vegetables are tender, remove the bacon and smoked sausage, slice thinly and set aside.\r\n\r\nIf you prefer a smooth consistency, purée the soup with a stick blender. Season to taste with salt and pepper. Add the meat back to the soup, setting some slices of rookworst aside.\r\n\r\nServe in heated bowls or soup plates, garnished with slices of rookworst and chopped celery leaf.\r\n\r\nEnjoy!',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/9ptx0a1565090843.jpg',
        strTags: 'Soup,Cake',
        strYoutube: 'https://www.youtube.com/watch?v=5YV0sJLtLt8',
        strIngredient1: 'Water',
        strIngredient2: 'Peas',
        strIngredient3: 'Pork',
        strIngredient4: 'Vegetable Stock Cube',
        strIngredient5: 'Celery',
        strIngredient6: 'Carrots',
        strIngredient7: 'Potatoes',
        strIngredient8: 'Onion',
        strIngredient9: 'Leek',
        strIngredient10: 'Celeriac',
        strIngredient11: 'Sausages',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '2L',
        strMeasure2: '300g',
        strMeasure3: '100g ',
        strMeasure4: '1',
        strMeasure5: '2',
        strMeasure6: '2',
        strMeasure7: '1 large',
        strMeasure8: '1 small',
        strMeasure9: '1 small',
        strMeasure10: '1 cup ',
        strMeasure11: '1 pound',
        strMeasure12: ' ',
        strMeasure13: ' ',
        strMeasure14: ' ',
        strMeasure15: ' ',
        strMeasure16: ' ',
        strMeasure17: ' ',
        strMeasure18: ' ',
        strMeasure19: ' ',
        strMeasure20: ' ',
        strSource:
          'https://www.thespruceeats.com/traditional-dutch-split-pea-soup-1129011',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52923',
        strMeal: 'Canadian Butter Tarts',
        Poster: '../../assets/images/food_6.jpg',
        strDrinkAlternate: null,
        strCategory: 'Dessert',
        strArea: 'Canadian',
        strInstructions:
          'Preheat the oven to fan 170C/ conventional 190C/gas 5. Roll out the pastry on a lightly floured surface so it’s slightly thinner than straight from the pack. Then cut out 18-20 rounds with a 7.5cm fluted cutter, re-rolling the trimmings. Use the rounds to line two deep 12-hole tart tins (not muffin tins). If you only have a regular-sized, 12-hole tart tin you will be able to make a few more slightly shallower tarts.\r\nBeat the eggs in a large bowl and combine with the rest of the ingredients except the walnuts. Tip this mixture into a pan and stir continuously for 3-4 minutes until the butter melts, and the mixture bubbles and starts to thicken. It should be thick enough to coat the back of a wooden spoon. Don’t overcook, and be sure to stir all the time as the mixture can easily burn. Remove from the heat and stir in the nuts.\r\nSpoon the filling into the unbaked tart shells so it’s level with the pastry. Bake for 15-18 minutes until set and pale golden. Leave in the tin to cool for a few minutes before lifting out on to a wire rack. Serve warm or cold.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/wpputp1511812960.jpg',
        strTags: 'Speciality,Snack,Desert,Pudding',
        strYoutube: 'https://www.youtube.com/watch?v=WUpaOGghOdo',
        strIngredient1: 'Shortcrust Pastry',
        strIngredient2: 'Eggs',
        strIngredient3: 'Muscovado Sugar',
        strIngredient4: 'Raisins',
        strIngredient5: 'Vanilla Extract',
        strIngredient6: 'Butter',
        strIngredient7: 'Single Cream',
        strIngredient8: 'Walnuts',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '375g',
        strMeasure2: '2 large',
        strMeasure3: '175g',
        strMeasure4: '100g ',
        strMeasure5: '1 tsp ',
        strMeasure6: '50g',
        strMeasure7: '4 tsp',
        strMeasure8: '50g',
        strMeasure9: '',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: '',
        strMeasure17: '',
        strMeasure18: '',
        strMeasure19: '',
        strMeasure20: '',
        strSource:
          'https://www.bbcgoodfood.com/recipes/1837/canadian-butter-tarts',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52848',
        strMeal: 'Bean & Sausage Hotpot',
        Poster: '../../assets/images/food_7.jpg',
        strDrinkAlternate: null,
        strCategory: 'Miscellaneous',
        strArea: 'British',
        strInstructions:
          'In a large casserole, fry the sausages until brown all over – about 10 mins.\r\n\r\nAdd the tomato sauce, stirring well, then stir in the beans, treacle or sugar and mustard. Bring to the simmer, cover and cook for 30 mins. Great served with crusty bread or rice.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/vxuyrx1511302687.jpg',
        strTags: null,
        strYoutube: 'https://www.youtube.com/watch?v=B0YX0yPX4Wo',
        strIngredient1: 'Sausages',
        strIngredient2: 'Tomato Sauce',
        strIngredient3: 'Butter Beans',
        strIngredient4: 'Black Treacle',
        strIngredient5: 'English Mustard',
        strIngredient6: '',
        strIngredient7: '',
        strIngredient8: '',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '8 large',
        strMeasure2: '1 Jar',
        strMeasure3: '1200g',
        strMeasure4: '1 tbls',
        strMeasure5: '1 tsp ',
        strMeasure6: '',
        strMeasure7: '',
        strMeasure8: '',
        strMeasure9: '',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: '',
        strMeasure17: '',
        strMeasure18: '',
        strMeasure19: '',
        strMeasure20: '',
        strSource:
          'https://www.bbcgoodfood.com/recipes/339607/bean-and-sausage-hotpot',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52942',
        strMeal: 'Roast fennel and aubergine paella',
        strDrinkAlternate: null,
        strCategory: 'Vegan',
        strArea: 'Spanish',
        strInstructions:
          '1 Put the fennel, aubergine, pepper and courgette in a roasting tray. Add a glug of olive oil, season with salt and pepper and toss around to coat the veggies in the oil. Roast in the oven for 20 minutes, turning a couple of times until the veg are pretty much cooked through and turning golden.\r\n\r\n2 Meanwhile, heat a paella pan or large frying pan over a low– medium heat and add a glug of olive oil. Sauté the onion for 8–10 minutes until softened. Increase the heat to medium and stir in the rice, paprika and saffron. Cook for around 1 minute to start toasting the rice, then add the white wine. Reduce by about half before stirring in two-thirds of the stock. Reduce to a simmer and cook for 10 minutes without a lid, stirring a couple of times.\r\n\r\n3 Stir in the peas, add some seasoning, then gently mix in the roasted veg. Pour over the remaining stock, arrange the lemon wedges on top and cover with a lid or some aluminium foil. Cook for a further 10 minutes.\r\n\r\n4 To ensure you get the classic layer of toasted rice at the bottom of the pan, increase the heat to high until you hear a slight crackle. Remove from the heat and sit for 5 minutes before sprinkling over the parsley and serving.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/1520081754.jpg',
        strTags: 'Vegan,Paella',
        strYoutube: 'https://www.youtube.com/watch?v=H5SmjR-fxUs',
        strIngredient1: 'Baby Aubergine',
        strIngredient2: 'Fennel',
        strIngredient3: 'Red Pepper',
        strIngredient4: 'Courgettes',
        strIngredient5: 'Onion',
        strIngredient6: 'Paella Rice',
        strIngredient7: 'Paprika',
        strIngredient8: 'Saffron',
        strIngredient9: 'White Wine',
        strIngredient10: 'Vegetable Stock',
        strIngredient11: 'Frozen Peas',
        strIngredient12: 'Lemon',
        strIngredient13: 'Parsley',
        strIngredient14: 'Salt',
        strIngredient15: 'Black Pepper',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '6 small',
        strMeasure2: '4 small',
        strMeasure3: '1 thinly sliced',
        strMeasure4: '1 medium',
        strMeasure5: '1 finely chopped ',
        strMeasure6: '300g',
        strMeasure7: '1 tsp ',
        strMeasure8: 'pinch',
        strMeasure9: '200ml',
        strMeasure10: '700ml',
        strMeasure11: '100g ',
        strMeasure12: '1 chopped',
        strMeasure13: 'Handful',
        strMeasure14: 'pinch',
        strMeasure15: 'pinch',
        strMeasure16: '',
        strMeasure17: '',
        strMeasure18: '',
        strMeasure19: '',
        strMeasure20: '',
        strSource:
          'https://www.homestylemag.co.uk/recipe/517/main-courses/roast-fennel-and-aubergine-paella',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  {
    meals: [
      {
        idMeal: '52764',
        strMeal: 'Garides Saganaki',
        strDrinkAlternate: null,
        strCategory: 'Seafood',
        strArea: 'Greek',
        strInstructions:
          'Place the prawns in a pot and add enough water to cover. Boil for 5 minutes. Drain, reserving the liquid, and set aside.\r\nHeat 2 tablespoons of oil in a saucepan. Add the onion; cook and stir until soft. Mix in the parsley, wine, tomatoes, garlic and remaining olive oil. Simmer, stirring occasionally, for about 30 minutes, or until the sauce is thickened.\r\nWhile the sauce is simmering, the prawns should become cool enough to handle. First remove the legs by pinching them, and then pull off the shells, leaving the head and tail on.\r\nWhen the sauce has thickened, stir in the prawns. Bring to a simmer again if the sauce has cooled with the prawns, and cook for about 5 minutes. Add the feta and remove from the heat. Let stand until the cheese starts to melt. Serve warm with slices of crusty bread.\r\nThough completely untraditional, you can add a few tablespoons of stock or passata to this recipe to make a delicious pasta sauce. Toss with pasta after adding the feta, and serve.',
        strMealThumb:
          'https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg',
        strTags: 'Seafood,Shellfish',
        strYoutube: 'https://www.youtube.com/watch?v=uO0ejc85zSE',
        strIngredient1: 'Raw king prawns',
        strIngredient2: 'Olive oil',
        strIngredient3: 'Chopped onion',
        strIngredient4: 'Freshly chopped parsley',
        strIngredient5: 'White wine',
        strIngredient6: 'Chopped tomatoes',
        strIngredient7: 'Minced garlic',
        strIngredient8: 'Cubed Feta cheese',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: null,
        strIngredient17: null,
        strIngredient18: null,
        strIngredient19: null,
        strIngredient20: null,
        strMeasure1: '500g',
        strMeasure2: '3 tablespoons',
        strMeasure3: '1',
        strMeasure4: 'pinch',
        strMeasure5: '250ml',
        strMeasure6: '1 (400g) tin',
        strMeasure7: '1/2 teaspoon',
        strMeasure8: '1 (200g) pack',
        strMeasure9: '',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: null,
        strMeasure17: null,
        strMeasure18: null,
        strMeasure19: null,
        strMeasure20: null,
        strSource: null,
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
];

export {dummy_data};
